### PR TITLE
Fix -1 compilation error on gnuradio 3.9

### PR DESCRIPTION
**Pull request by bkerler**
This patch will resolve the compilation error on gnuradio-3.9,  '_1' was not declared in this scope.

### CODE REVIEW

**Comment by marcidy** [comment]
Applying these changes fixed the build issue I had using pybombs with gnuradio3.9, thanks!

**Comment by Sec42** [comment]
I'm a bit confused, because I can build gr-iridium maint-3.9 (2ba89ed318) just fine using the maint-3.9 gnuradio branch (fbfbee7e05). Can you give a bit more info about your system and sources?

**Comment by marcidy** [comment]
This is probably related to pybomb recipes pointing to master instead of main-3.9

I applied these changes on top of 65810ca (master when I grabbed it),   pybombs currently pulls master for gr-iridium, so I was not on maint-3.9. 

gr-iridium.lwr:
```yaml
category: common
depends:
- gnuradio
- scipy
- gr-osmosdr
description: GNU Radio iridium burst detector and demodulator
gitbranch: master
inherit: cmake
source: git+https://github.com/muccc/gr-iridium.git
```
The pybomb recipes don't seem to be in sync with which releases target which gr version.  I believe this is being worked on and I caught a set of commits that aren't consistent across all components.

I think this would be resolved via the recipes pointing to the appropriate branch rather than needing this fix.  I'll double check this works later this week by updating the recipe locally.  If I still get a compilation issue I'll follow up.

This is probably a false alarm, sorry about that.

**Comment by Sec42** [comment]
I also tried building gr-iridium master (65810cad56) with the "maint-3.9" gnuradio sources, and it also builds fine for me. So there must be another difference... -- Can you share a bit more about your system? (OS/Distribution, etc.)

**Comment by marcidy** [comment]
Debian 11 (Bullseye)
Linux Moog 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
CMake 3.18.4
g++ (Debian 10.2.1-6) 10.2.1 20210110
gcc (Debian 10.2.1-6) 10.2.1 20210110
c++ (Debian 10.2.1-6) 10.2.1 20210110
libboost 1.74.0-9

Sorry, not sure what else might be interesting, just let me know what you need

**Comment by bkerler** [comment]
This error happens on newest gcc because of the stricter c++ rules if you build gnuradio 3.9 from master branch. Not just this project is affected, it's pretty well known and documented already for multiple gnuradio modules.

**Comment by Sec42** [comment]
I will look into getting a newer gcc to reproduce this issue.

**Comment by Sec42** [comment]
I was finally able to reproduce it by installing debian-11 in a VM. As far as I can tell, the issue has now been resolved in current master by getting rid of the boost usage altogether in commit 1329a6e7a9e993dc63c8a573c65b1472a382e486

Please let me know if you still have compile issues after that.

**Pull request closed without merging**
