### PR TITLE
USRP DBSRX support

### PR DESCRIPTION
**Pull request by takgr**
USRP DBSRX ADC pga gain support and USRP example configuration

### CODE REVIEW

**Comment by Sec42** [comment]
Looks ok from my POV, probably needs testing if all the other configs still work after the remove of toupper(). -> off to schneider.

**Comment by schneider42** [comment]
@takgr: Is there a reason why you want to set the ADC PGA gain specifically?

I've just attached an USRP1 with an RFX1800 (which provides an additional `PGA0` gain) and tested how UHD handles it. Just setting the the virtual gain `gain` will first turn up the `PGA0` gain until it saturates and then turn up the `ADC-pga` gain until that is at its limit.

The DBSRX provides two additional gains `GC1` and `GC2`. My assumption is that UHD will take care of these just as it does for the `PGA0` gain of the RFX1800.

Can you execute the following Python script on your machine and report the output:

```
#!/usr/bin/env python
import osmosdr
source = osmosdr.source()
gains = source.get_gain_names()
print gains
for gain in range(100):
    source.set_gain(gain, 0)
    print ["%d" % source.get_gain(gain_name, 0) for gain_name in gains]
```

**Comment by takgr** [comment]
@schneider42: 
Here is the output of the Python script:
('ADC-pga', 'GC1', 'BBG')
['0', '0', '0']
['0', '1', '0']
['0', '1', '0']
['0', '3', '0']
['0', '3', '0']
['0', '5', '0']
['0', '5', '0']
['0', '7', '0']
['0', '7', '0']
['0', '9', '0']
['0', '9', '0']
['0', '11', '0']
['0', '11', '0']
['0', '13', '0']
['0', '14', '0']
['0', '15', '0']
['0', '15', '0']
['0', '17', '0']
['0', '18', '0']
['0', '19', '0']
['0', '19', '0']
['0', '20', '0']
['0', '22', '0']
['0', '22', '0']
['0', '24', '0']
['0', '24', '0']
['0', '26', '0']
['0', '26', '0']
['0', '28', '0']
['0', '29', '0']
['0', '30', '0']
['0', '31', '0']
['0', '32', '0']
['0', '33', '0']
['0', '34', '0']
['0', '35', '0']
['0', '36', '0']
['0', '37', '0']
['0', '38', '0']
['0', '39', '0']
['0', '39', '0']
['0', '41', '0']
['0', '42', '0']
['0', '43', '0']
['0', '44', '0']
['0', '45', '0']
['0', '46', '0']
['0', '47', '0']
['0', '48', '0']
['0', '49', '0']
['0', '50', '0']
['0', '51', '0']
['0', '52', '0']
['0', '53', '0']
['0', '54', '0']
['0', '55', '0']
['0', '56', '0']
['0', '57', '0']
['0', '58', '0']
['0', '59', '0']
['0', '60', '0']
['0', '61', '0']
['0', '62', '0']
['0', '63', '0']
['0', '64', '0']
['0', '65', '0']
['0', '66', '0']
['0', '67', '0']
['0', '68', '0']
['0', '69', '0']
['0', '70', '0']
['0', '71', '0']
['0', '72', '0']
['0', '73', '0']
['0', '73', '1']
['0', '73', '2']
['0', '73', '3']
['0', '73', '4']
['0', '73', '5']
['0', '73', '6']
['0', '73', '7']
['0', '73', '8']
['0', '73', '9']
['0', '73', '10']
['0', '73', '11']
['0', '73', '12']
['0', '73', '13']
['0', '73', '14']
['0', '73', '15']
['1', '73', '15']
['2', '73', '15']
['3', '73', '15']
['4', '73', '15']
['5', '73', '15']
['6', '73', '15']
['7', '73', '15']
['8', '73', '15']
['9', '73', '15']
['10', '73', '15']
['11', '73', '15']


The sequence is GC1, BBG and then ADC-pga, that seems correct as [discussed here](https://lists.gnu.org/archive/html/discuss-gnuradio/2005-12/msg00236.html). However 
I wanted to be able to set them explicitly because I have noticed after many many tests that most messages are decoded when GC1 gain is no more than 60-65dB and ADC-pga at about 15-20. An explanation might be that since the installation is in a noisy environment without any filters the DBSRX LNA might get saturated after 65dB's of gain.
Either way, being able to set multiple gain stages is a feature and unless it breaks anything else I see no reason why not providing the ability to do so.

**Comment by schneider42** [comment]
@takgr: I've merged this as https://github.com/muccc/gr-iridium/commit/7b0e9dcfd13533592fd5b6d3f41d38a56e248825

Sorry, github did not get that this is the the matching PR.

**Pull request closed without merging**
